import { useState } from 'react';
import { api, uid, date, type Course, type CourseDetail, type Topic, type SourceRef } from './api';
import { Icon, Modal, Empty, RichText } from './components';
export type Run=<T>(label:string,fn:()=>Promise<T>)=>Promise<T|undefined>;
export function CourseForm({initial,onSave,onClose,run,busy}:{initial:Course;onSave:(value:Course)=>Promise<void>;onClose:()=>void;run:Run;busy:boolean}){
  const [value,setValue]=useState({...initial}),[fetched,setFetched]=useState(false);
  const safeClose=()=>{if(JSON.stringify(value)===JSON.stringify(initial)||confirm('Chiudere senza salvare le modifiche alla materia?'))onClose();};
  return <Modal title={initial.id?'Informazioni della materia':'Nuova materia'} onClose={safeClose} wide><form className="form-body" onSubmit={e=>{e.preventDefault();void onSave(value);}}>
    <label>Nome della materia<input required autoFocus maxLength={200} value={value.title} onChange={e=>setValue({...value,title:e.target.value})} placeholder="Es. Analisi matematica II"/></label>
    <label>Descrizione personale <span className="muted">facoltativa</span><textarea rows={2} maxLength={20000} value={value.description} onChange={e=>setValue({...value,description:e.target.value})} placeholder="Note, indicazioni del docente, obiettivi personali…"/></label>
    <label>Pagina dell’insegnamento<div className="input-action"><input type="url" value={value.syllabusUrl||''} onChange={e=>setValue({...value,syllabusUrl:e.target.value})} placeholder="https://…"/><button type="button" disabled={busy||!value.syllabusUrl} onClick={()=>void run('Lettura della pagina del corso',async()=>{const result=await api('syllabus.fetch',value.syllabusUrl);setValue(v=>({...v,syllabus:result.text,syllabusUrl:result.url,fetchedAt:result.fetchedAt}));setFetched(true);})}>Importa testo</button></div></label>
    {fetched&&<p className="hint">Controlla il testo importato e rimuovi le parti estranee al programma prima di salvare.</p>}
    <label>Programma ufficiale<textarea rows={10} maxLength={100000} value={value.syllabus} onChange={e=>setValue({...value,syllabus:e.target.value})} placeholder="Incolla obiettivi formativi, contenuti e modalità d’esame. Saranno il riferimento principale per l’albero."/></label>
    <p className="hint">Il programma può essere completato dopo. Le slide non devono essere tutte disponibili per iniziare.</p>
    <footer className="modal-actions"><button type="button" onClick={safeClose}>Annulla</button><button className="primary" disabled={busy||!value.title.trim()}>Salva materia</button></footer>
  </form></Modal>;
}
function branchIds(tree:Topic[],id:string){const ids=new Set([id]);for(let i=0;i<tree.length;i++)for(const n of tree)if(n.parentId&&ids.has(n.parentId))ids.add(n.id);return ids;}
export function TreeList({tree,onOpen,editing=false,onMove,onAdd}:{tree:Topic[];onOpen:(topic:Topic)=>void;editing?:boolean;onMove?:(id:string,direction:number)=>void;onAdd?:(parentId:string)=>void}){
  const render=(parentId:string|null,depth:number)=><div className={`tree-level ${depth?'nested':''}`}>{tree.filter(n=>n.parentId===parentId).map((node,index)=>{const done=node.parts.filter(p=>p.checked).length;return <div className="tree-branch" key={node.id}><div className="tree-row"><button className="topic-open" onClick={()=>onOpen(node)}><span className={`node-marker ${node.parts.length&&done===node.parts.length?'complete':''}`}>{node.parts.length&&done===node.parts.length?<Icon name="check" size={13}/>:String(index+1).padStart(2,'0')}</span><span className="node-title">{node.title}<small>{node.origin==='proposal'?'Struttura proposta':node.sources.length?`${node.sources.length} riferimenti ai materiali`:'Materiali da aggiungere'}</small></span><span className="node-progress">{done}/{node.parts.length}</span><Icon name="chevron" size={15}/></button>{editing&&<div className="tree-tools"><button aria-label={`Sposta ${node.title} in alto`} title="Sposta in alto" onClick={()=>onMove?.(node.id,-1)}>↑</button><button aria-label={`Sposta ${node.title} in basso`} title="Sposta in basso" onClick={()=>onMove?.(node.id,1)}>↓</button><button title="Aggiungi sottoargomento" onClick={()=>onAdd?.(node.id)}>+</button></div>}</div>{render(node.id,depth+1)}</div>;})}</div>;
  return render(null,0);
}
function TopicEditor({topic,detail,onSave,onClose,busy}:{topic:Topic;detail:CourseDetail;onSave:(topic:Topic)=>void;onClose:()=>void;busy:boolean}){
  const [value,setValue]=useState({...topic}),[parts,setParts]=useState(topic.parts.map(p=>p.label).join('\n'));
  const forbidden=branchIds(detail.tree,topic.id);
  const updateRef=(i:number,key:keyof SourceRef,v:string|number)=>setValue({...value,sources:value.sources.map((r,j)=>j===i?{...r,[key]:v}:r)});
  return <Modal title={detail.tree.some(n=>n.id===topic.id)?'Modifica argomento':'Nuovo argomento'} onClose={onClose} wide><form className="form-body" onSubmit={e=>{e.preventDefault();const next=parts.split('\n').map(s=>s.trim()).filter(Boolean).map(label=>value.parts.find(p=>p.label===label)||{id:uid(),label,checked:false});onSave({...value,parts:next});}}>
    <label>Titolo<input required maxLength={250} value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/></label>
    <label>Posizione nell’albero<select value={value.parentId||''} onChange={e=>setValue({...value,parentId:e.target.value||null})}><option value="">Macroargomento principale</option>{detail.tree.filter(n=>!forbidden.has(n.id)).map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label>
    <label>Descrizione<textarea rows={3} maxLength={12000} value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></label>
    <label>Parti da studiare <span className="muted">una per riga</span><textarea rows={5} value={parts} onChange={e=>setParts(e.target.value)}/></label><p className="hint">Le parti rinominate ripartono senza check. Le parti invariate conservano il tuo stato.</p>
    <label>Provenienza<select value={value.origin} onChange={e=>setValue({...value,origin:e.target.value as Topic['origin']})}><option value="program">Programma ufficiale</option><option value="slides">Materiali del corso</option><option value="proposal">Proposta / struttura personale</option></select></label>
    <div className="section-heading"><h3>Riferimenti ai materiali</h3><button type="button" disabled={!detail.documents.length} onClick={()=>setValue({...value,sources:[...value.sources,{documentId:detail.documents[0].id,from:1,to:1}]})}>Aggiungi</button></div>
    {value.sources.map((ref,i)=><div className="source-edit" key={i}><select aria-label="Documento del riferimento" value={ref.documentId} onChange={e=>updateRef(i,'documentId',e.target.value)}>{detail.documents.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><input aria-label="Pagina iniziale" type="number" min={1} max={detail.documents.find(d=>d.id===ref.documentId)?.pages} value={ref.from} onChange={e=>updateRef(i,'from',Number(e.target.value))}/><span>–</span><input aria-label="Pagina finale" type="number" min={ref.from} max={detail.documents.find(d=>d.id===ref.documentId)?.pages} value={ref.to} onChange={e=>updateRef(i,'to',Number(e.target.value))}/><button type="button" className="icon-button" aria-label="Rimuovi riferimento" onClick={()=>setValue({...value,sources:value.sources.filter((_,j)=>j!==i)})}><Icon name="close" size={15}/></button></div>)}
    <footer className="modal-actions"><button type="button" onClick={onClose}>Annulla</button><button className="primary" disabled={busy||!value.title.trim()}>Salva argomento</button></footer>
  </form></Modal>;
}
export function CourseView({detail,onChange,onStudy,onQuiz,onOpenQuiz,onEdit,run,busy,model}:{detail:CourseDetail;onChange:(d:CourseDetail)=>void;onStudy:(topic:Topic|null,ref?:SourceRef)=>void;onQuiz:(topic:Topic,count:number)=>void;onOpenQuiz:(id:string)=>void;onEdit:()=>void;run:Run;busy:boolean;model:string}){
  const [tab,setTab]=useState('tree'),[selected,setSelected]=useState<string|null>(null),[editor,setEditor]=useState<Topic|null>(null),[ordering,setOrdering]=useState(false),[draftOpen,setDraftOpen]=useState(false),[quizzes,setQuizzes]=useState<any[]>([]),[count,setCount]=useState(5);
  const topic=detail.tree.find(n=>n.id===selected),parts=detail.tree.flatMap(n=>n.parts),done=parts.filter(p=>p.checked).length;
  const saveTree=(tree:Topic[])=>run('Salvataggio del percorso',async()=>onChange(await api('tree.save',{courseId:detail.course.id,tree})));
  function add(parentId:string|null){setEditor({id:uid(),parentId,title:'',description:'',origin:'proposal',parts:[],sources:[]});}
  function move(id:string,direction:number){const node=detail.tree.find(n=>n.id===id)!;const siblings=detail.tree.filter(n=>n.parentId===node.parentId),at=siblings.findIndex(n=>n.id===id),other=siblings[at+direction];if(!other)return;const tree=[...detail.tree],a=tree.findIndex(n=>n.id===id),b=tree.findIndex(n=>n.id===other.id);[tree[a],tree[b]]=[tree[b],tree[a]];void saveTree(tree);}
  const setSection=(value:string)=>{setTab(value);if(value==='quizzes')void run('',async()=>setQuizzes(await api('quiz.list',detail.course.id)));};
  return <>
    <header className="page-header"><div><h1>{detail.course.title}</h1>{detail.course.description&&<p className="description">{detail.course.description}</p>}</div><div className="header-actions"><button onClick={onEdit} disabled={busy}><Icon name="edit" size={15}/> Modifica</button><button className="icon-button" title="Esporta materia e materiali" disabled={busy} onClick={()=>void run('Esportazione della materia',()=>api('course.export',detail.course.id))}><Icon name="upload"/></button></div></header>
    <nav className="tabs" aria-label="Sezioni della materia">{[['tree','Percorso'],['materials','Materiali'],['program','Programma'],['quizzes','Verifiche']].map(([key,label])=><button className={tab===key?'active':''} key={key} onClick={()=>setSection(key)}>{label}</button>)}</nav>
    {tab==='tree'&&<section className="course-section"><div className="section-heading"><div><h2>Il percorso di studio</h2><p>{done} / {parts.length}</p></div><div className="row-actions"><button disabled={busy} onClick={()=>setOrdering(v=>!v)}>{ordering?'Fine':'Ordina'}</button><button disabled={busy} onClick={()=>add(null)}><Icon name="plus" size={15}/> Argomento</button><button className="primary" disabled={busy||!model||!detail.course.syllabus.trim()} title={!model?'Collega ChatGPT nelle impostazioni':!detail.course.syllabus.trim()?'Aggiungi il programma ufficiale':''} onClick={()=>void run('Generazione del percorso',async()=>{onChange(await api('tree.generate',{courseId:detail.course.id,model}));setDraftOpen(true);})}>{detail.tree.length?'Aggiorna con AI':'Genera con AI'}</button></div></div>
      {detail.draft&&<div className="inline-notice"><span>Una proposta del percorso è pronta da rivedere.</span><button onClick={()=>setDraftOpen(true)}>Rivedi proposta <Icon name="arrow" size={14}/></button></div>}
      {detail.treeStale&&detail.tree.length>0&&!detail.draft&&<p className="hint status-note">Il programma o i materiali sono cambiati. Puoi aggiornare il percorso con l’AI; i tuoi check restano sotto il tuo controllo.</p>}
      {!!parts.length&&<div className="progress-track" aria-label={`${done} parti studiate su ${parts.length}`}><div style={{width:`${done/parts.length*100}%`}}/></div>}
      {!detail.tree.length?<Empty title="Un percorso, prima di partire." action={<button disabled={busy} onClick={onEdit}>Aggiungi il programma</button>}>Il programma ufficiale definisce gli argomenti. Le slide li collegano al modo in cui vengono trattati. Puoi anche costruire l’albero a mano.</Empty>:<TreeList tree={detail.tree} onOpen={n=>setSelected(n.id)} editing={ordering&&!busy} onMove={move} onAdd={add}/>}
    </section>}
    {tab==='materials'&&<section className="course-section"><div className="section-heading"><div><h2>I materiali del corso</h2><p>PDF, appunti TXT e Markdown. Gli originali vengono copiati nell’archivio locale.</p></div><button className="primary" disabled={busy} onClick={()=>void run('Importazione dei materiali',async()=>{const result=await api('documents.import',detail.course.id);if(result){onChange(result.detail);const errors=result.results.filter((r:any)=>r.error);if(errors.length)throw new Error(errors.map((r:any)=>`${r.name}: ${r.error}`).join('\n'));}})}><Icon name="plus" size={16}/> Aggiungi materiali</button></div>
      {!detail.documents.length?<Empty title="Aggiungi il primo plico di slide">Puoi iniziare con i materiali già disponibili e aggiungerne altri durante il corso.</Empty>:<div className="document-list">{detail.documents.map(doc=><div className="document-row" key={doc.id}><span className="document-icon"><Icon name="file" size={22}/></span><button className="document-name" onClick={()=>onStudy(null,{documentId:doc.id,from:1,to:1})}><strong>{doc.name}</strong><span>{doc.kind==='pdf'?`${doc.pages} pagine`:'Appunti'} · {date(doc.addedAt)}{doc.emptyPages?` · ${doc.emptyPages} pagine con testo scarso o assente`:''}</span></button><button onClick={()=>onStudy(null,{documentId:doc.id,from:1,to:1})}>Apri</button><button className="icon-button danger" aria-label={`Rimuovi ${doc.name}`} disabled={busy} onClick={()=>{if(confirm(`Rimuovere “${doc.name}” dall’archivio? Il file originale non verrà toccato.`))void run('Rimozione del materiale',async()=>onChange(await api('documents.delete',doc.id)));}}><Icon name="trash" size={16}/></button></div>)}</div>}
      
    </section>}
    {tab==='program'&&<section className="course-section program-section"><div className="section-heading"><div><h2>Programma ufficiale</h2><p>La fonte principale del tuo percorso.</p></div><button disabled={busy} onClick={onEdit}>Modifica programma</button></div>{detail.course.syllabusUrl&&<button className="text-button" onClick={()=>void api('link.open',detail.course.syllabusUrl)}>Pagina dell’insegnamento ↗</button>}{detail.course.fetchedAt&&<p className="hint">Testo importato il {date(detail.course.fetchedAt)}. Non si aggiorna automaticamente.</p>}{detail.course.syllabus?<div className="program-text"><RichText text={detail.course.syllabus}/></div>:<Empty title="Il programma non c’è ancora">Incollalo dalla pagina dell’insegnamento o importalo tramite URL.</Empty>}</section>}
    {tab==='quizzes'&&<section className="course-section"><div className="section-heading"><div><h2>Le tue verifiche</h2><p>I risultati non modificano i check del percorso.</p></div></div>{!quizzes.length?<Empty title="La prima verifica parte da un argomento">Apri un nodo del percorso e scegli Test. Le prove e le risposte rimarranno qui.</Empty>:<div className="quiz-list">{quizzes.map(q=><button className="quiz-row" key={q.id} onClick={()=>onOpenQuiz(q.id)}><span><strong>{q.title}</strong><small>{date(q.createdAt)} · {q.total} domande</small></span><span className="badge">{q.status==='draft'?'Da completare':q.graded<q.total?'Correzione da completare':'Consegnata'}</span><Icon name="chevron" size={16}/></button>)}</div>}</section>}
    {topic&&!editor&&<Modal title={topic.title} onClose={()=>setSelected(null)}><div className="modal-body"><div className="modal-meta"><span className="badge">{topic.origin==='program'?'Dal programma':topic.origin==='slides'?'Dai materiali':'Proposta'}</span><div className="row-actions"><button className="text-button" disabled={busy} onClick={()=>setEditor(topic)}>Modifica</button><button className="icon-button danger" aria-label="Elimina argomento" disabled={busy} onClick={()=>{if(confirm("Eliminare questo argomento e tutti i suoi sottoargomenti?")){const ids=branchIds(detail.tree,topic.id);void saveTree(detail.tree.filter(n=>!ids.has(n.id)));setSelected(null);}}}><Icon name="trash" size={15}/></button></div></div>{topic.description&&<RichText text={topic.description}/>}<h3 className="small-heading">PARTI STUDIATE</h3><div className="checklist">{topic.parts.map(part=><label key={part.id}><input type="checkbox" checked={part.checked} disabled={busy} onChange={e=>{const checked=e.target.checked;onChange({...detail,tree:detail.tree.map(n=>n.id===topic.id?{...n,parts:n.parts.map(p=>p.id===part.id?{...p,checked}:p)}:n)});void run('',async()=>{try{onChange(await api('tree.check',{courseId:detail.course.id,topicId:topic.id,partId:part.id,checked}));}catch(error){onChange(detail);throw error;}});}}/><span>{part.label}</span></label>)}{!topic.parts.length&&<p className="hint">Aggiungi le parti da studiare con Modifica.</p>}</div><h3 className="small-heading">MATERIALI COLLEGATI</h3><div className="source-list">{topic.sources.map((ref,i)=><button key={i} onClick={()=>{setSelected(null);onStudy(topic,ref);}}><Icon name="file" size={15}/>{detail.documents.find(d=>d.id===ref.documentId)?.name} · p. {ref.from}{ref.to!==ref.from?`–${ref.to}`:''}</button>)}{!topic.sources.length&&<p className="hint">Nessun materiale collegato per ora.</p>}</div><div className="test-choice"><label>Domande nel test<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[3,5,8,12].map(n=><option key={n} value={n}>{n} domande ed esercizi</option>)}</select></label></div></div><footer className="modal-actions"><button disabled={busy||!model} onClick={()=>{setSelected(null);onQuiz(topic,count);}}>Test</button><button className="primary" disabled={busy} onClick={()=>{setSelected(null);onStudy(topic);}}>Studia <Icon name="arrow" size={15}/></button></footer></Modal>}
    {editor&&<TopicEditor topic={editor} detail={detail} busy={busy} onClose={()=>setEditor(null)} onSave={next=>void run('Salvataggio dell’argomento',async()=>{const tree=detail.tree.some(n=>n.id===next.id)?detail.tree.map(n=>n.id===next.id?next:n):[...detail.tree,next];onChange(await api('tree.save',{courseId:detail.course.id,tree}));setEditor(null);})}/>}
    {draftOpen&&detail.draft&&<Modal title="Rivedi il percorso proposto" onClose={()=>setDraftOpen(false)} wide><div className="modal-body"><p className="hint">La proposta sostituisce la struttura attuale solo dopo la tua conferma. I check vengono conservati per argomenti e parti rimasti invariati.</p><div className="draft-counts"><span>{detail.draft.nodes.length} argomenti proposti</span><span>{detail.tree.filter(n=>!detail.draft!.nodes.some(d=>d.id===n.id)).length} argomenti sostituiti o rimossi</span></div>{detail.draft.notes&&<div className="draft-notes"><RichText text={detail.draft.notes}/></div>}<TreeList tree={detail.draft.nodes} onOpen={()=>{}}/></div><footer className="modal-actions"><button disabled={busy} onClick={()=>void run('',async()=>{onChange(await api('tree.discard',detail.course.id));setDraftOpen(false);})}>Scarta proposta</button><button className="primary" disabled={busy} onClick={()=>void run('Applicazione del percorso',async()=>{onChange(await api('tree.apply',detail.course.id));setDraftOpen(false);})}>Applica percorso</button></footer></Modal>}

  </>;
}
