import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createPortal } from 'react-dom';
import { api, date, type Course, type CourseDetail, type Topic, type SourceRef, type PublicQuiz, type AccountStatus, type Model } from './api';
import { Icon, Modal, Spinner } from './components';
import { CourseView, CourseForm, type Run } from './CourseView';
import { StudyView } from './StudyView';
import { QuizView } from './QuizView';
import './style.css';
import brandMark from '../assets/mark.svg';
const blank:Course={id:'',title:'',description:'',syllabus:'',updatedAt:''};
function App(){
  const [courses,setCourses]=useState<Course[]>([]),[detail,setDetail]=useState<CourseDetail|null>(null),[view,setView]=useState<'library'|'course'|'study'|'quiz'>('library');
  const [topic,setTopic]=useState<Topic|null>(null),[source,setSource]=useState<SourceRef|undefined>(),[quiz,setQuiz]=useState<PublicQuiz|null>(null);
  const [form,setForm]=useState<Course|null>(null),[settings,setSettings]=useState(false),[account,setAccount]=useState<AccountStatus>({signedIn:false,accounts:[]}),[accountId,setAccountId]=useState(''),[models,setModels]=useState<Model[]>([]),[model,setModel]=useState('');
  const [busy,setBusy]=useState(false),[activity,setActivity]=useState(''),[progress,setProgress]=useState(''),[error,setError]=useState(''),[search,setSearch]=useState(''),[initialized,setInitialized]=useState(false);
  const run:Run=async(label,fn)=>{setError('');setBusy(true);setActivity(label);try{return await fn();}catch(e){setError(e instanceof Error?e.message:'Operazione non riuscita.');return undefined;}finally{setBusy(false);setActivity('');setProgress('');}};
  async function refreshModels(preferred?:string){const list=await api<Model[]>('auth.models');setModels(list);const chosen=list.some(m=>m.id===(preferred||model))?(preferred||model):list[0]?.id||'';setModel(chosen);if(chosen)await api('settings.model',chosen);}
  useEffect(()=>{
    void run('',async()=>{const state=await api('app.state');setCourses(state.courses);setAccount(state.auth);if(state.auth.warning)setError(state.auth.warning);setAccountId(state.auth.active||'');setModel(state.model);setInitialized(true);if(state.auth.signedIn)await refreshModels(state.model);});
    return window.study?.onEvent(event=>{if(event.type==='progress')setProgress(event.message||'');});
  },[]);
  const openCourse=(id:string)=>void run('',async()=>{setDetail(await api('course.get',id));setView('course');});
  const changed=(d:CourseDetail)=>{setDetail(d);setCourses(old=>old.map(c=>c.id===d.course.id?d.course:c));};
  function study(t:Topic|null,ref?:SourceRef){setTopic(t);setSource(ref);setView('study');}
  async function saveCourse(value:Course){await run('Salvataggio della materia',async()=>{const saved=await api<Course>('course.save',value);setCourses(await api('courses.list'));setDetail(await api('course.get',saved.id));setForm(null);setView('course');});}
  const goQuiz=(t:Topic,count:number)=>void run('Preparazione della verifica',async()=>{const result=await api<PublicQuiz>('quiz.create',{courseId:detail!.course.id,topicId:t.id,count,model});setQuiz(result);setView('quiz');});
  const openQuiz=(id:string)=>void run('',async()=>{setQuiz(await api('quiz.get',id));setView('quiz');});
  const filtered=courses.filter(c=>c.title.toLowerCase().includes(search.toLowerCase()));
  return <div className={`app-shell ${view==='study'?'studying':''}`}>
    <aside className="sidebar"><button className="brand" onClick={()=>{if(!busy)setView('library');}}><img className="brand-mark" src={brandMark} alt=""/><span>stemhelp</span></button><button className={`library-link ${view==='library'?'active':''}`} disabled={busy} onClick={()=>setView('library')}><Icon name="book" size={17}/> Le mie materie</button><div className="sidebar-label">MATERIE<button className="icon-button" aria-label="Nuova materia" disabled={busy} onClick={()=>setForm({...blank})}><Icon name="plus" size={15}/></button></div><nav className="course-nav">{courses.map(c=><button key={c.id} disabled={busy} className={detail?.course.id===c.id&&view!=='library'?'active':''} onClick={()=>openCourse(c.id)}><span className="course-dot"/>{c.title}</button>)}</nav><div className="sidebar-bottom"><span className="local-label"><span/> Salvato sul computer</span><button className="settings-link" onClick={()=>setSettings(true)}><Icon name="settings" size={17}/><span>Impostazioni<small>{account.signedIn?'ChatGPT collegato':'Collega ChatGPT'}</small></span><span className={`account-dot ${account.signedIn?'connected':''}`}/></button></div></aside>
    <main className={view==='study'?'main-study':'main-content'}>
      {view==='library'&&<><header className="page-header"><div><h1>Le mie materie</h1></div><button className="primary" disabled={busy} onClick={()=>setForm({...blank})}><Icon name="plus" size={16}/> Nuova materia</button></header><div className="library-toolbar"><label className="search"><Icon name="search" size={16}/><input aria-label="Cerca materia" placeholder="Cerca una materia" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{!initialized?<div className="loading"><Spinner/> Apertura archivio</div>:!courses.length?null:!filtered.length?<p className="muted">Nessuna materia corrisponde alla ricerca.</p>:<div className="course-grid">{filtered.map((c,i)=><button className="course-card" disabled={busy} key={c.id} onClick={()=>openCourse(c.id)}><div className="course-card-top"><span>{String(i+1).padStart(2,'0')}</span><Icon name="book" size={21}/></div><h2>{c.title}</h2><p>{c.description|| (c.syllabus?'Programma del corso disponibile':'Aggiungi il programma per iniziare')}</p><footer><span>Aggiornata il {date(c.updatedAt)}</span><Icon name="arrow" size={17}/></footer></button>)}</div>}</>}
      {view==='course'&&detail&&<CourseView key={detail.course.id} detail={detail} onChange={changed} onStudy={study} onQuiz={goQuiz} onOpenQuiz={openQuiz} onEdit={()=>setForm(detail.course)} run={run} busy={busy} model={model}/>}
      {view==='study'&&detail&&<StudyView key={detail.course.id+':'+(topic?.id||'')+':'+(source?.documentId||'')} detail={detail} topic={topic} initialSource={source} model={model} busy={busy} run={run} onBack={()=>setView('course')} onError={setError}/>}
      {view==='quiz'&&detail&&quiz&&<QuizView key={quiz.id} initial={quiz} model={model} busy={busy} run={run} onBack={()=>setView('course')} onSource={(documentId,page)=>study(detail.tree.find(t=>t.id===quiz.topicId)||null,{documentId,from:page,to:page})}/>}
    </main>
    {error&&createPortal(<div className="error-toast" role="alert"><div><strong>Non è stato possibile completare l’operazione</strong><p>{error}</p></div><button className="icon-button" aria-label="Chiudi errore" onClick={()=>setError('')}><Icon name="close" size={15}/></button></div>,document.querySelector('dialog[open]')||document.body)}
    {busy&&(activity||progress)&&createPortal(<div className="activity" role="status"><Spinner/><span>{progress||activity}</span><button onClick={()=>{void api('operation.cancel');void api('auth.cancel');}}>Interrompi</button></div>,document.querySelector('dialog[open]')||document.body)}
    {form&&<CourseForm initial={form} onSave={saveCourse} onClose={()=>{if(!busy)setForm(null);}} run={run} busy={busy}/>}
    {settings&&<Modal title="Impostazioni" onClose={()=>setSettings(false)}><div className="modal-body settings-body"><h3>Account ChatGPT</h3><p className="hint">Usa il tuo piano per il tutor, il percorso e le verifiche. L’utilizzo è condiviso con le altre app collegate.</p><div className="account-status"><span className={`account-dot ${account.signedIn?'connected':''}`}/>{account.signedIn?'Account collegato':'Nessun account collegato'}</div>{account.accounts.length>0&&<label>Account<select value={accountId} disabled={busy} onChange={e=>setAccountId(e.target.value)}><option value="">Aggiungi un account</option>{account.accounts.map(a=><option value={a.id} key={a.id}>{a.label}</option>)}</select></label>}<div className="row-actions"><button disabled={busy} className="chatgpt-button" onClick={()=>void run('Completa l’accesso nel browser',async()=>{try{const status=await api<AccountStatus>('auth.login',{id:accountId||undefined});setAccount(status);setAccountId(status.active||'');await refreshModels();}finally{setAccount(await api('auth.status'));}})}>Continue with ChatGPT</button>{account.signedIn&&<button disabled={busy} onClick={()=>void run('Disconnessione',async()=>{const status=await api<AccountStatus>('auth.logout');setAccount(status);setModels([]);setModel('');if(status.warning)setError(status.warning);})}>Disconnetti</button>}</div>{busy&&activity.includes('accesso')&&<button onClick={()=>void api('auth.cancel')}>Annulla accesso</button>}
      <label>Modello<div className="input-action"><select value={model} disabled={busy||!models.length} onChange={e=>{const value=e.target.value;void run('',async()=>{await api('settings.model',value);setModel(value);});}}><option value="">{account.signedIn?'Scegli un modello':'Accedi prima a ChatGPT'}</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><button disabled={busy||!account.signedIn} onClick={()=>void run('Aggiornamento modelli',()=>refreshModels())}>Aggiorna</button></div></label><button className="text-button" onClick={()=>void api('usage.open')}>Gestisci utilizzo e limiti in ChatGPT ↗</button>
      <hr/><h3>Dati e contesto</h3><button className="text-button" disabled={busy} onClick={()=>void run('Importazione della materia',async()=>{const d=await api<CourseDetail|null>('course.import');if(d){setCourses(await api('courses.list'));setDetail(d);setView('course');setSettings(false);}})}><Icon name="upload" size={15}/> Importa archivio</button><p className="hint">Materie, PDF, check e verifiche rimangono sul computer. Il tutor riceve il programma e i passaggi necessari alla richiesta. Le chat si azzerano con Nuova chat o alla chiusura; il contesto del corso rimane.</p><p className="hint">Puoi esportare ogni materia in un archivio .study dal pulsante in alto nella materia. Le credenziali non sono incluse.</p>
      {detail&&<><hr/><h3>Materia corrente</h3><button className="danger" disabled={busy} onClick={()=>{if(confirm(`Eliminare “${detail.course.title}”, i materiali archiviati e tutte le verifiche? Questa operazione non si può annullare. Esporta prima la materia se vuoi conservarla.`))void run('Eliminazione della materia',async()=>{await api('course.delete',detail.course.id);setCourses(await api('courses.list'));setDetail(null);setView('library');setSettings(false);});}}><Icon name="trash" size={15}/> Elimina {detail.course.title}</button></>}
      <p className="version">stemhelp 1.0 · Archivio locale</p></div></Modal>}
  </div>;
}
class AppBoundary extends React.Component<{children:React.ReactNode},{failed:boolean}> {
  state={failed:false};
  static getDerivedStateFromError(){return {failed:true};}
  render(){return this.state.failed?<main className="main-content"><h1>Riapri il quadernone</h1><p>L’interfaccia ha incontrato un errore. Le materie, i materiali e le verifiche già salvati restano sul computer.</p><button onClick={()=>location.reload()}>Ricarica stemhelp</button></main>:this.props.children;}
}
createRoot(document.getElementById('root')!).render(<AppBoundary><App/></AppBoundary>);
